Added routes for user settings CRUD
Digital-Intelligence-Unit/NHS_Business_Intelligence_Platform_Api pull request #101
Opened 2022-07-27 16:52 UTC by luket-nhs

2022-07-28 07:27 UTC, morgans3 requested changes

2022-07-28 07:27 UTC, morgans3 commented on routes/usersettings.js
> +const UserSettingsModel = new DIULibrary.Models.UserSettingsModel();
This does not exist, are you using the latest version of DIULibrary?

2022-08-04 15:44 UTC, luket-nhs commented on routes/usersettings.js
> +const UserSettingsModel = new DIULibrary.Models.UserSettingsModel();
The diu-data-functions library needed updating to 1.2.34 first, that's now done.

2022-08-08 07:51 UTC, morgans3 approved these changes

2022-08-08 07:51 UTC, merged